export const POPULAR_CITIES = [
  'Chh. Sambhajinagar',
  'Mumbai',
  'Pune',
  'Delhi NCR',
  'Ahmedabad',
  'Surat',
  'Vadodara',
  'Rajkot',
  'Nagpur',
  'Nashik',
  'Thane',
  'Indore',
  'Jaipur',
  'Bengaluru',
  'Hyderabad',
  'Kolkata',
];

export const POPULAR_EVENTS = [
  // Chh. Sambhajinagar (Aurangabad)
  { name: 'Aurangabad Dandiya Mahotsav', city: 'Chh. Sambhajinagar', venue: 'Jabinda Estate Ground' },
  { name: 'Prozone Navratri Utsav', city: 'Chh. Sambhajinagar', venue: 'Prozone Mall Grounds' },
  { name: 'Royal Marathwada Garba', city: 'Chh. Sambhajinagar', venue: 'Kalagram Cultural Ground' },

  // Mumbai
  { name: 'Dome Dandiya - NSCI', city: 'Mumbai', venue: 'SVP Stadium, Worli' },
  { name: 'Falguni Pathak Garba Mahotsav', city: 'Mumbai', venue: 'Late Shri Pramod Mahajan Ground, Borivali' },
  { name: 'Kora Kendra Navratri', city: 'Mumbai', venue: 'Kora Kendra Grounds, Borivali' },
  { name: 'Radiance Dandiya', city: 'Mumbai', venue: 'Hotel Sahara Star' },
  { name: 'Naidu Club Navratri', city: 'Mumbai', venue: 'Kora Kendra, Borivali' },

  // Pune
  { name: 'Pune Dandiya Utsav', city: 'Pune', venue: 'Deccan Gymkhana' },
  { name: 'Royal Garba Night Pune', city: 'Pune', venue: 'Balkrishna Lawns, Mundhwa' },
  { name: 'Phoenix Dandiya Fest', city: 'Pune', venue: 'Phoenix Marketcity, Viman Nagar' },
  { name: 'Garba Dandiya Raas', city: 'Pune', venue: 'Mahalaxmi Lawns, Karve Nagar' },

  // Delhi NCR
  { name: 'Dandiya Masti Delhi', city: 'Delhi NCR', venue: 'Rajwada Palace, GT Karnal Road' },
  { name: 'Pacific Dandiya Nights', city: 'Delhi NCR', venue: 'Pacific Mall, Tagore Garden' },
  { name: 'Delhi Gujarati Samaj Garba', city: 'Delhi NCR', venue: 'Civil Lines, Delhi' },
  { name: 'Kingdom Dandiya Utsav', city: 'Delhi NCR', venue: 'Sector 29, Gurugram' },

  // Gujarat
  { name: 'United Way of Baroda', city: 'Vadodara', venue: 'VCA Stadium / Atladra' },
  { name: 'Maa Shakti Garba Mahotsav', city: 'Vadodara', venue: 'Gujarat Housing Board Ground' },
  { name: 'Shankus Dandiya Fest', city: 'Ahmedabad', venue: 'Shankus Water Park Grounds' },
  { name: 'Mirchi Rock N Dhol', city: 'Ahmedabad', venue: 'Aman Akash Party Plot' },
  { name: 'Surat Royal Navratri Mahotsav', city: 'Surat', venue: 'VR Surat Grounds' },
  { name: 'Heritage Raas Rajkot', city: 'Rajkot', venue: 'Race Course Ground' },

  // Other Major Cities
  { name: 'Indore Dandiya Nights', city: 'Indore', venue: 'Abhay Prashal Stadium' },
  { name: 'Jaipur Royal Garba', city: 'Jaipur', venue: 'Entertainment Paradise' },
  { name: 'Nagpur Dandiya Carnival', city: 'Nagpur', venue: 'Reshimbagh Ground' },
  { name: 'Nashik Grand Navratri', city: 'Nashik', venue: 'Golf Club Ground' },
];

export const DUMMY_USERS = [
  // ===================== CHH. SAMBHAJINAGAR =====================
  {
    id: 'user-cs-tanvi-01',
    naam: 'Tanvi Deshmukh',
    gender: 'Female',
    city: 'Chh. Sambhajinagar',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Energetic',
    whatsapp: '9823011223',
    instagram: 'tanvi_garba_cs',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Prozone Navratri Utsav',
    has_partner: false,
    language: 'hi',
    bio: 'Garba & Dandiya lover in Sambhajinagar! Prozone passes booked. Looking for an energetic partner for couple rounds.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-cs-sakshi-02',
    naam: 'Sakshi Kulkarni',
    gender: 'Female',
    city: 'Chh. Sambhajinagar',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Traditional',
    whatsapp: '9823044556',
    instagram: 'sakshi_raas',
    photo_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Royal Marathwada Garba',
    has_partner: false,
    language: 'hi',
    bio: '3-taali and traditional Gujarati-Marathi fusion steps. Kalagram ground confirmed!',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-cs-rohan-03',
    naam: 'Rohan Jadhav',
    gender: 'Male',
    city: 'Chh. Sambhajinagar',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Chill',
    whatsapp: '9823077889',
    instagram: 'rohan_jadhav_cs',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Aurangabad Dandiya Mahotsav',
    has_partner: false,
    language: 'hi',
    bio: 'Dhol beats lover! Attending Aurangabad Dandiya Mahotsav, looking for a cheerful dance partner.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-cs-omkar-04',
    naam: 'Omkar Shinde',
    gender: 'Male',
    city: 'Chh. Sambhajinagar',
    age_group: '25-35',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9823099001',
    instagram: 'omkar_spins',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Prozone Navratri Utsav',
    has_partner: false,
    language: 'hi',
    bio: 'Can spin non-stop till 1 AM! Looking for a fast-paced partner in Chh. Sambhajinagar.',
    created_at: new Date().toISOString(),
  },

  // ===================== PUNE =====================
  {
    id: 'user-ananya-18',
    naam: 'Ananya Deshmukh',
    gender: 'Female',
    city: 'Pune',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Energetic',
    whatsapp: '9822012345',
    instagram: 'ananya_pune_beats',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Pune Dandiya Utsav',
    has_partner: false,
    language: 'hi',
    bio: 'Deccan Gymkhana Dandiya pass confirmed! Looking for a fun dance partner.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-sayali-pune-02',
    naam: 'Sayali Joshi',
    gender: 'Female',
    city: 'Pune',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9822033445',
    instagram: 'sayali_garba_pune',
    photo_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Phoenix Dandiya Fest',
    has_partner: false,
    language: 'hi',
    bio: 'Sanedo & Dodhiya fan! Attending Phoenix Dandiya Fest. Looking for a partner who loves fast spins.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-aditya-19',
    naam: 'Aditya Kulkarni',
    gender: 'Male',
    city: 'Pune',
    age_group: '25-35',
    dancing_level: 'Intermediate',
    vibe: 'Chill',
    whatsapp: '9822998877',
    instagram: 'aditya_pune',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Pune Dandiya Utsav',
    has_partner: false,
    language: 'hi',
    bio: 'Love dancing and street food hopping after garba. Looking for a partner in Pune.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-siddharth-pune-04',
    naam: 'Siddharth More',
    gender: 'Male',
    city: 'Pune',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Traditional',
    whatsapp: '9822055667',
    instagram: 'sid_pune_garba',
    photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Royal Garba Night Pune',
    has_partner: false,
    language: 'hi',
    bio: 'Attending Balkrishna Lawns Garba. Looking for good vibes & synchronized dandiya rounds.',
    created_at: new Date().toISOString(),
  },

  // ===================== MUMBAI =====================
  {
    id: 'user-rhea-04',
    naam: 'Rhea Merchant',
    gender: 'Female',
    city: 'Mumbai',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9820012345',
    instagram: 'rhea_raas',
    photo_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Dome Dandiya - NSCI',
    has_partner: false,
    language: 'en',
    bio: 'Dome Dandiya pass is confirmed! Looking for a partner who has great timing and energy.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-neha-mumbai-02',
    naam: 'Neha Mehta',
    gender: 'Female',
    city: 'Mumbai',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Traditional',
    whatsapp: '9820033445',
    instagram: 'neha_borivali_garba',
    photo_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Falguni Pathak Garba Mahotsav',
    has_partner: false,
    language: 'gu',
    bio: 'Borivali Falguni Pathak ground season pass booked! Chaniya choli ready, looking for a garba partner.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-kavya-mumbai-03',
    naam: 'Kavya Shah',
    gender: 'Female',
    city: 'Mumbai',
    age_group: '25-35',
    dancing_level: 'Intermediate',
    vibe: 'Chill',
    whatsapp: '9820066778',
    instagram: 'kavya_mumbai',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Kora Kendra Navratri',
    has_partner: false,
    language: 'gu',
    bio: 'Kora Kendra lover. Looking for someone who enjoys smooth folk rhythm and 2-taali steps.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-sameer-05',
    naam: 'Sameer Joshi',
    gender: 'Male',
    city: 'Mumbai',
    age_group: '25-35',
    dancing_level: 'Intermediate',
    vibe: 'Chill',
    whatsapp: '9820987654',
    instagram: 'sameer_mumbai_garba',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Falguni Pathak Garba Mahotsav',
    has_partner: false,
    language: 'en',
    bio: 'Late night garba + Ghatkopar khau galli plan! Looking for someone who enjoys the festival vibe.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-varun-mumbai-05',
    naam: 'Varun Somaiya',
    gender: 'Male',
    city: 'Mumbai',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9820088990',
    instagram: 'varun_dandiya_pro',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Dome Dandiya - NSCI',
    has_partner: false,
    language: 'en',
    bio: 'Non-stop energy till 2 AM! Looking for a fast-spinning partner for NSCI Dome.',
    created_at: new Date().toISOString(),
  },

  // ===================== DELHI NCR =====================
  {
    id: 'user-delhi-ananya-01',
    naam: 'Ananya Gupta',
    gender: 'Female',
    city: 'Delhi NCR',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Energetic',
    whatsapp: '9811012345',
    instagram: 'ananya_delhi_garba',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Delhi Gujarati Samaj Garba',
    has_partner: false,
    language: 'hi',
    bio: 'Delhi Gujarati Samaj garba pass ready! Seeking a fun partner for 2-taali & 3-taali steps.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-delhi-mehak-02',
    naam: 'Mehak Chawla',
    gender: 'Female',
    city: 'Delhi NCR',
    age_group: '25-35',
    dancing_level: 'Beginner',
    vibe: 'Chill',
    whatsapp: '9811044556',
    instagram: 'mehak_c_delhi',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Dandiya Masti Delhi',
    has_partner: false,
    language: 'hi',
    bio: 'First time at Dandiya Masti! Looking for someone friendly who knows the rhythm and steps.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-delhi-kabir-03',
    naam: 'Kabir Mehta',
    gender: 'Male',
    city: 'Delhi NCR',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9811077889',
    instagram: 'kabir_garba_delhi',
    photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Pacific Dandiya Nights',
    has_partner: false,
    language: 'hi',
    bio: 'Traditional kediya ready. Looking for a high-energy partner for Pacific Dandiya Nights in Delhi!',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-delhi-arjun-04',
    naam: 'Arjun Kapoor',
    gender: 'Male',
    city: 'Delhi NCR',
    age_group: '25-35',
    dancing_level: 'Intermediate',
    vibe: 'Traditional',
    whatsapp: '9811099001',
    instagram: 'arjun_dandiya_ncr',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Kingdom Dandiya Utsav',
    has_partner: false,
    language: 'hi',
    bio: 'Gurugram & Delhi Dandiya enthusiast. Let us spin together in rhythm this Navratri 2026!',
    created_at: new Date().toISOString(),
  },

  // ===================== AHMEDABAD =====================
  {
    id: 'user-priya-01',
    naam: 'Priya Sharma',
    gender: 'Female',
    city: 'Ahmedabad',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9825012345',
    instagram: 'priyagarbaqueen',
    photo_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Shankus Dandiya Fest',
    has_partner: false,
    language: 'en',
    bio: 'Sanedo lover! Looking for someone who can match my 3-taali energy till 2 AM.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-kinjal-09',
    naam: 'Kinjal Dave',
    gender: 'Female',
    city: 'Ahmedabad',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Traditional',
    whatsapp: '9825445566',
    instagram: 'kinjal_garba_girl',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Mirchi Rock N Dhol',
    has_partner: false,
    language: 'gu',
    bio: 'Love traditional Chaniya Choli and synchronized 3-taali steps! Let us swirl together.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-rohan-02',
    naam: 'Rohan Patel',
    gender: 'Male',
    city: 'Ahmedabad',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Energetic',
    whatsapp: '9879098765',
    instagram: 'rohan_dandiya',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Mirchi Rock N Dhol',
    has_partner: false,
    language: 'gu',
    bio: 'Traditional Kediya ready chhe. Looking for a partner for Mirchi Rock N Dhol!',
    created_at: new Date().toISOString(),
  },

  // ===================== VADODARA =====================
  {
    id: 'user-diya-03',
    naam: 'Diya Trivedi',
    gender: 'Female',
    city: 'Vadodara',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Traditional',
    whatsapp: '9909012345',
    instagram: 'diya_united_way',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    event_pin: 'United Way of Baroda',
    has_partner: false,
    language: 'gu',
    bio: 'Baroda girl born with dandiya in hands. United Way pass booked! Lets spin together.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-manan-11',
    naam: 'Manan Shah',
    gender: 'Male',
    city: 'Vadodara',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9909112233',
    instagram: 'manan_baroda_garba',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    event_pin: 'United Way of Baroda',
    has_partner: false,
    language: 'gu',
    bio: 'Non-stop dhol beats only. Baroda garba has no match!',
    created_at: new Date().toISOString(),
  },

  // ===================== SURAT =====================
  {
    id: 'user-khushi-06',
    naam: 'Khushi Choksi',
    gender: 'Female',
    city: 'Surat',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Energetic',
    whatsapp: '9879123456',
    instagram: 'khushisuratgarba',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Surat Royal Navratri Mahotsav',
    has_partner: false,
    language: 'gu',
    bio: 'Garba lovers of Surat! Looking for a dance partner with full enthusiasm.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-chirag-13',
    naam: 'Chirag Zaveri',
    gender: 'Male',
    city: 'Surat',
    age_group: '18-25',
    dancing_level: 'Intermediate',
    vibe: 'Chill',
    whatsapp: '9879998877',
    instagram: 'chirag_surat_beats',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Surat Royal Navratri Mahotsav',
    has_partner: false,
    language: 'gu',
    bio: 'Surat diamond city garba fan! Looking for a pleasant partner for group rounds.',
    created_at: new Date().toISOString(),
  },

  // ===================== RAJKOT =====================
  {
    id: 'user-pooja-16',
    naam: 'Pooja Jadeja',
    gender: 'Female',
    city: 'Rajkot',
    age_group: '18-25',
    dancing_level: 'Pro',
    vibe: 'Traditional',
    whatsapp: '9824012345',
    instagram: 'pooja_rajkot_raas',
    photo_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Heritage Raas Rajkot',
    has_partner: false,
    language: 'gu',
    bio: 'Kathiawadi Raas enthusiast! Seeking someone who loves authentic Saurashtra dhol beats.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-jay-17',
    naam: 'Jaydeep Parmar',
    gender: 'Male',
    city: 'Rajkot',
    age_group: '25-35',
    dancing_level: 'Pro',
    vibe: 'Energetic',
    whatsapp: '9824998877',
    instagram: 'jay_rajkot_garba',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    event_pin: 'Heritage Raas Rajkot',
    has_partner: false,
    language: 'gu',
    bio: 'Non stop Raas garba at Race Course Ground! Looking for a high stamina female partner.',
    created_at: new Date().toISOString(),
  },
];
